### ISSUE TITLE
JID Read Instance Not Declared Properly

### ISSUE THREAD

**Issue by DrewBarclay** [pontarius/pontarius-xmpp#102]
Attempting to, for example, `read` an empty list of JIDs, will fail. 

The error can be found in Network.Xmpp.Types.hs. Specifically:

[] -> error "Expected `parseJid \"<jid>\"'"

According to Text.Read's documentation, the readsPrec function should return an empty list in this case, but this line instead errors.

**Comment by Philonous** [comment]
Thanks for reporting this. I pushed a fix to master
