### ISSUE TITLE
Tests fail because files are not exposed

### ISSUE THREAD

**Issue by Profpatsch** [pontarius/pontarius-xmpp#105]
The test files are not exposed in the caba file, so the hackage distribution is broken https://hackage.haskell.org/package/pontarius-xmpp-0.5.2/src/

**Comment by Philonous** [comment]
Should be fixed in a89afd42a6c0c917710fb8398fdc42ce739d297b

**Comment by Profpatsch** [comment]
Will you create a new release?

**Comment by Philonous** [comment]
I already did: http://hackage.haskell.org/package/pontarius-xmpp-0.5.3
