### ISSUE TITLE
Dead contact link in README

### ISSUE THREAD

**Issue by jmazon** [pontarius/pontarius-xmpp#120]
README.md's last section, “More Information”, links to www.jonkri.com, which doesn't resolve.

**Comment by Neustradamus** [comment]
@jonkri: How to contact you now?

**Comment by jonkri** [comment]
@jmazon, @Neustradamus:

Sorry for not responding to this earlier!

The contact information was removed in https://github.com/pontarius/pontarius-xmpp/commit/90f06f7130c6d984db46ea5f2a7a128a774a9fd3.

I’m no longer working on this project, but @l29ah has an active fork at https://github.com/l29ah/pontarius-xmpp.

If you want to contact me in some other matter, I can be reached via @jonkri:matrix.org.

Take care! 🙂
