### ISSUE TITLE
can't compile 0.4.2.2

### ISSUE THREAD

**Issue by l29ah** [pontarius/pontarius-xmpp#91]
source/Network/Xmpp/Tls.hs:114:25:
    Couldn't match type ‘m0 Context’ with ‘Context’
    Expected type: m Context
      Actual type: rng0 -> m0 Context
    In the expression: contextNew backend params
    In an equation for ‘client’:
        client params backend = contextNew backend params

**Comment by Philonous** [comment]
This is due to the tls version bound beeing too lax. You can work around this by passing --constraint "tls > 1.3" to cabal. I'll submit a fix shortly.

**Comment by Philonous** [comment]
Should be fixed by eb4eb3f133228281d2328c4e8dd6bbbbf17743a7 and is uploaded to hackage
