### ISSUE TITLE
Session support doesn't check stream features

### ISSUE THREAD

**Issue by xnyhps** [pontarius/pontarius-xmpp#94]
The requirement to send an IQ after logging in with

    <session xmlns='urn:ietf:params:xml:ns:xmpp-session'/>

was removed in RFC 6121.

pontarius-xmpp does not check if `xmpp-session` support is advertised by the server in the stream features, it will send the IQ unless `establishSession` in `sessionStreamConfiguration` is set to `False`. However, that is inconvenient if the library is used for user-configured servers. Additionally, there is a [draft](https://tools.ietf.org/html/draft-cridland-xmpp-session-01) that specifies an `<optional/>` element for the stream feature to indicate that the server follows 6121 and session establishment is not needed and a number of server implementations follow this.

I think it would be better to remove the `establishSession` setting and only send this IQ if the server uses the stream feature without an `<optional/>` element.

**Comment by Philonous** [comment]
Thanks for reporting this. The establishSession option was mostly a hack to make pontarius-xmpp work with ejabberd. It now checks the stream features and should hopefully work out-of-the-box.
