### ISSUE TITLE
Support connecting to UNIX sockets

### ISSUE THREAD

**Issue by singpolyma** [pontarius/pontarius-xmpp#97]
Instead of just INET sockets

**Comment by Philonous** [comment]
This is already possible by setting connectionDetails to [UseConnection](http://hackage.haskell.org/package/pontarius-xmpp-0.4.5/docs/Network-Xmpp.html#v:UseConnection) and writing the connection procedure by hand.

**Comment by singpolyma** [comment]
Hmm.  I suppose that's true.  I'll close this for now
